#!/usr/bin/env node

/**
 * Build-time version injection for TempoTune web app.
 *
 * Reads the semantic version from package.json and the current git commit hash,
 * then generates version.generated.ts with an APP_VERSION constant.
 *
 * Also sets NEXT_PUBLIC_APP_VERSION for Sentry release integration.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const PACKAGE_JSON = path.join(ROOT, 'package.json');
const VERSION_FILE = path.join(ROOT, 'version.generated.ts');

function getVersion() {
  const pkg = JSON.parse(fs.readFileSync(PACKAGE_JSON, 'utf8'));
  return pkg.version;
}

function getCommitHash() {
  if (process.env.COMMIT_HASH) {
    return process.env.COMMIT_HASH;
  }
  try {
    return execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
  } catch {
    return 'unknown';
  }
}

function main() {
  const version = getVersion();
  const commitHash = getCommitHash();
  const appVersion = `tempotune-web-${version}-${commitHash}`;

  const content = [
    '// Auto-generated by scripts/inject-version.js — do not edit manually.',
    `export const APP_VERSION = '${appVersion}';`,
    '',
  ].join('\n');

  fs.writeFileSync(VERSION_FILE, content, 'utf8');
  console.log(`Generated version.generated.ts → APP_VERSION = '${appVersion}'`);

  // In CI, write NEXT_PUBLIC_APP_VERSION and DEPLOYMENT_VERSION to GITHUB_ENV
  if (process.env.GITHUB_ENV) {
    fs.appendFileSync(
      process.env.GITHUB_ENV,
      `NEXT_PUBLIC_APP_VERSION=${appVersion}\nDEPLOYMENT_VERSION=${appVersion}\n`,
    );
    console.log(`Wrote NEXT_PUBLIC_APP_VERSION and DEPLOYMENT_VERSION to GITHUB_ENV`);
  }
}

main();
