#!/bin/bash
# Auto-detect dev machine IP and merge with .env to generate config

SCRIPT_DIR="$(dirname "$0")"
ENV_FILE="$SCRIPT_DIR/../.env"
CONFIG_FILE="$SCRIPT_DIR/../src/config.generated.ts"

# Defaults
PROD_WEB_URL="https://your-production-url.com"
DEV_SERVER_PORT="3000"
ANDROID_EMULATOR_HOST="10.0.2.2"

# Read .env if it exists
if [ -f "$ENV_FILE" ]; then
  while IFS='=' read -r key value; do
    # Skip comments and empty lines
    [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
    # Trim whitespace
    key=$(echo "$key" | xargs)
    value=$(echo "$value" | xargs)
    case "$key" in
      PROD_WEB_URL) PROD_WEB_URL="$value" ;;
      DEV_SERVER_PORT) DEV_SERVER_PORT="$value" ;;
      ANDROID_EMULATOR_HOST) ANDROID_EMULATOR_HOST="$value" ;;
    esac
  done < "$ENV_FILE"
fi

# Auto-detect local IP
DEV_MACHINE_IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null)

if [ -z "$DEV_MACHINE_IP" ]; then
  echo "Warning: Could not detect local IP. Falling back to localhost."
  DEV_MACHINE_IP="localhost"
fi

cat > "$CONFIG_FILE" <<EOF
// Auto-generated by scripts/generate-dev-config.sh
// Do not edit manually — update .env and re-run the script to regenerate.
export const DEV_MACHINE_IP = '$DEV_MACHINE_IP';
export const DEV_SERVER_PORT = $DEV_SERVER_PORT;
export const PROD_WEB_URL = '$PROD_WEB_URL';
export const ANDROID_EMULATOR_HOST = '$ANDROID_EMULATOR_HOST';
EOF

echo "Generated dev config: IP=$DEV_MACHINE_IP PORT=$DEV_SERVER_PORT PROD=$PROD_WEB_URL"
