#!/bin/bash
# Auto-detect dev machine IP and merge with .env to generate config

SCRIPT_DIR="$(dirname "$0")"
ENV_FILE="$SCRIPT_DIR/../.env"
CONFIG_FILE="$SCRIPT_DIR/../src/config.generated.ts"

# Defaults
PROD_WEB_URL="https://your-production-url.com"
DEV_SERVER_PORT="3000"
ENV_ANDROID_DEV_HOST=""
RUNTIME_ANDROID_DEV_HOST="${ANDROID_EMULATOR_HOST:-}"
QA_USE_DEV_WEB_URL="${QA_USE_DEV_WEB_URL:-0}"
QA_ENABLE_WEBVIEW_DEBUGGING="${QA_ENABLE_WEBVIEW_DEBUGGING:-0}"
QA_WEB_URL="${QA_WEB_URL:-}"

# Read .env if it exists
if [ -f "$ENV_FILE" ]; then
  while IFS='=' read -r key value; do
    # Skip comments and empty lines
    [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
    # Trim whitespace
    key=$(echo "$key" | xargs)
    value=$(echo "$value" | xargs)
    case "$key" in
      PROD_WEB_URL) PROD_WEB_URL="$value" ;;
      DEV_SERVER_PORT) DEV_SERVER_PORT="$value" ;;
      ANDROID_EMULATOR_HOST) ENV_ANDROID_DEV_HOST="$value" ;;
      QA_WEB_URL) QA_WEB_URL="$value" ;;
    esac
  done < "$ENV_FILE"
fi

# Auto-detect local IP
DEV_MACHINE_IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null)

if [ -z "$DEV_MACHINE_IP" ]; then
  echo "Warning: Could not detect local IP. Falling back to localhost."
  DEV_MACHINE_IP="localhost"
fi

detect_android_dev_host() {
  if ! command -v adb &>/dev/null; then
    echo "10.0.2.2"
    return
  fi

  local devices
  local has_emulator=0
  local has_physical_device=0

  devices="$(adb devices -l 2>/dev/null || true)"

  while IFS= read -r line; do
    [[ -z "$line" || "$line" =~ ^List ]] && continue
    [[ "$line" != *$'\tdevice'* ]] && continue

    local serial
    serial="${line%%[[:space:]]*}"

    if [[ "$serial" == emulator-* ]] || [[ "$line" == *"emulator"* ]]; then
      has_emulator=1
    else
      has_physical_device=1
    fi
  done <<< "$devices"

  if [ "$has_emulator" -eq 1 ]; then
    echo "10.0.2.2"
  elif [ "$has_physical_device" -eq 1 ]; then
    echo "$DEV_MACHINE_IP"
  else
    echo "10.0.2.2"
  fi
}

if [ -n "$RUNTIME_ANDROID_DEV_HOST" ]; then
  ANDROID_EMULATOR_HOST="$RUNTIME_ANDROID_DEV_HOST"
elif [ -n "$ENV_ANDROID_DEV_HOST" ]; then
  ANDROID_EMULATOR_HOST="$ENV_ANDROID_DEV_HOST"
else
  ANDROID_EMULATOR_HOST="$(detect_android_dev_host)"
fi

cat > "$CONFIG_FILE" <<EOF
// Auto-generated by scripts/generate-dev-config.sh
// Do not edit manually — update .env and re-run the script to regenerate.
export const DEV_MACHINE_IP = '$DEV_MACHINE_IP';
export const DEV_SERVER_PORT = $DEV_SERVER_PORT;
export const PROD_WEB_URL = '$PROD_WEB_URL';
export const ANDROID_EMULATOR_HOST = '$ANDROID_EMULATOR_HOST';
export const QA_USE_DEV_WEB_URL = $([ "$QA_USE_DEV_WEB_URL" = "1" ] && echo "true" || echo "false");
export const QA_ENABLE_WEBVIEW_DEBUGGING = $([ "$QA_ENABLE_WEBVIEW_DEBUGGING" = "1" ] && echo "true" || echo "false");
export const QA_WEB_URL = '$QA_WEB_URL';
EOF

echo "Generated dev config: IP=$DEV_MACHINE_IP PORT=$DEV_SERVER_PORT PROD=$PROD_WEB_URL QA_USE_DEV_WEB_URL=$QA_USE_DEV_WEB_URL QA_ENABLE_WEBVIEW_DEBUGGING=$QA_ENABLE_WEBVIEW_DEBUGGING QA_WEB_URL=$QA_WEB_URL"
